FROM php:8.2-apache

# Instala dependencias necesarias
RUN apt-get update && apt-get install -y \
    libgmp-dev \
    libzip-dev \
    zip \
    unzip \
    libonig-dev \
    libxml2-dev \
    libpng-dev \
    && docker-php-ext-install \
        bcmath \
        gmp \
        mysqli \
        pdo \
        pdo_mysql \
        zip

# Habilita mod_rewrite para Apache
RUN a2enmod rewrite

# Permite .htaccess
RUN sed -i 's/AllowOverride None/AllowOverride All/i' /etc/apache2/apache2.conf

# Copia el código al contenedor
COPY . /var/www/html/

# Asigna permisos adecuados
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Expone el puerto 80
EXPOSE 80
